const data = {
  products: [
    {
      name: 'Caneca Branca',
      slug: 'caneca-branca',
      category: 'canecas',
      image: '/images/caneca-branca.jpg',
      brand: 'Sonhos Personalizados',
      countInStock: 10,
      description: 'Caneca branca de porcelana',
      price: 50,
      rating: 4.5,
      numReviews: 8,
    },
    {
      name: 'Squeeze',
      slug: 'squeeze',
      category: 'squeezes',
      image: '/images/squeeze-1.jpg',
      brand: 'Sonhos Personalizados',
      countInStock: 10,
      description: 'Squeeze de plástico',
      price: 50,
      rating: 4.5,
      numReviews: 8,
    },

    {
      name: 'Quadro 20x30',
      slug: 'quadro-20x30',
      category: 'quadros',
      image: '/images/quadro-20x30.jpg',
      brand: 'Sonhos Personalizados',
      countInStock: 10,
      description: 'Quadro personalizado',
      price: 50,
      rating: 4.5,
      numReviews: 8,
    },
    {
      name: 'Caneta personalizada',
      slug: 'caneta-personalizada',
      category: 'canetas',
      image: '/images/caneta-1.jpg',
      brand: 'Sonhos Personalizados',
      countInStock: 10,
      description: 'Caneta de plástico personalizada',
      price: 50,
      rating: 4.5,
      numReviews: 8,
    },
    {
      name: 'Chinelo personalizado',
      slug: 'chinelos-personalizados',
      category: 'chinelos',
      image: '/images/chinelo-1.jpg',
      brand: 'Sonhos Personalizados',
      countInStock: 10,
      description: 'Chinelos personalizados de borracha',
      price: 50,
      rating: 4.5,
      numReviews: 8,
    },
    {
      name: 'Copo Gin',
      slug: 'copo-gin',
      category: 'copos',
      image: '/images/copo-gin-1.jpg',
      brand: 'Sonhos Personalizados',
      countInStock: 10,
      description: 'Copo de gin personalizado',
      price: 50,
      rating: 4.5,
      numReviews: 8,
    },
  ],
};

export default data;
